// Code generated by "stringer -type=MissingAction -output generated_options.go"; DO NOT EDIT.

package template

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-1]
	_ = x[ZeroValue-2]
	_ = x[Error-4]
}

const (
	_MissingAction_name_0 = "InvalidZeroValue"
	_MissingAction_name_1 = "Error"
)

var (
	_MissingAction_index_0 = [...]uint8{0, 7, 16}
)

func (i MissingAction) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _MissingAction_name_0[_MissingAction_index_0[i]:_MissingAction_index_0[i+1]]
	case i == 4:
		return _MissingAction_name_1
	default:
		return "MissingAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
