// Code generated by "stringer -type=ErrorSource -output generated_errors.go"; DO NOT EDIT.

package template

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FieldError-1]
	_ = x[CallError-2]
}

const _ErrorSource_name = "FieldErrorCallError"

var _ErrorSource_index = [...]uint8{0, 10, 19}

func (i ErrorSource) String() string {
	i -= 1
	if i >= ErrorSource(len(_ErrorSource_index)-1) {
		return "ErrorSource(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ErrorSource_name[_ErrorSource_index[i]:_ErrorSource_index[i+1]]
}
