// Code generated by "stringer -type=ErrorAction -output generated_actions.go"; DO NOT EDIT.

package template

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoReplace-0]
	_ = x[ResultReplaced-1]
	_ = x[ResultAsArray-2]
}

const _ErrorAction_name = "NoReplaceResultReplacedResultAsArray"

var _ErrorAction_index = [...]uint8{0, 9, 23, 36}

func (i ErrorAction) String() string {
	if i >= ErrorAction(len(_ErrorAction_index)-1) {
		return "ErrorAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorAction_name[_ErrorAction_index[i]:_ErrorAction_index[i+1]]
}
